title: EMBEDIN Terminal
description: >-
  The Blackbox Astron Log â€” Embedded Linux, Rust, and Real-Time Systems.
  All the views and thoughts are my own!

baseurl: ""
url: "https://embedin.github.io"

theme: minima

plugins:
  - jekyll-feed

header_pages: 
  - about_this_site.md
  - about_me.md

defaults:
  values:
    author: "Venkata Naga Ravikiran Bulusu"

sass:
  sass_dir: assets/css
  style: compressed
