title: EMBEDIN
description: >-
  Welcome to EMBEDIN blog!
  Here you can explore concise insights into embedded systems, distilled from practical work experience.
  All the views and thoughts are my own!

baseurl: ""
url: ""

theme: minima

plugins:
  - jekyll-feed

header_pages: 
  - about_this_site.md
  - about_me.md

defaults:
  values:
    author: "Venkata Naga Ravikiran Bulusu"

sass:
  sass_dir: assets/css
  style: compressed
